name: Fetch TFVC Files

on:
  push:

jobs:
  fetch-tfvc-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: | 
        npm install @actions/github
        npm install xlsx
        npm install axios

    - name: Fetch TFVC Projects
      id: fetch-tfvc-projects
      uses: actions/github-script@v6
      with:
        script: |
          // Script for TFC files from all projects.
          //const axios = require('axios');
          //const fs = require('fs');
          
          console.log('Inside try');
          const response = await fetch('https://dev.azure.com/rudra099999/_apis/tfvc/items?api-version=7.2-preview.1', {
            method: 'GET',
            headers: {
              'Content-Type': 'application/json',
              'Authorization': 'Basic' + btoa(`:${{ secrets.ADO_TOKEN }}`)
            }
          });
          if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
          }
          const data = await response.json();
          console.log(data);
          core.setOutput('PROJECT_LIST',data);
          } catch (error) {
            console.log('Inside catch');
            console.error('Error fetching projects:', error);
            core.setOutput('PROJECT_LIST',-1);
          }

    - name: Get TFVC Items
      id: get-tfvc-items
      uses: actions/github-script@v6
      with:
        script: |
          //Script to get all TFVC items in a project
          const project_list = ${{ steps.fetch-tfvc-projects.outputs.PROJECT_LIST }}
          console.log(projecct_list);

