name: Bulk Migration Script

on:
  workflow_dispatch:

jobs:
  get-latest-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: | 
        npm install @actions/github
        npm install xlsx

    - name: Migrate Bulk repos
      uses: actions/github-script@v6
      with:
        script: |
          // Script for migration all repos form ADO to Github mentioned in excel File.
          const XLSX = require('xlsx');
          const fs = require('fs');
          const { execSync } = require('child_process');
          
          // Load Excel file
          const workbook = XLSX.readFile('./data/DummyDataToTestADOMigration.xlsx');
          const sheetName = workbook.SheetNames[0];
          const worksheet = workbook.Sheets[sheetName];
          const failedRepos = [];

          // Convert Excel to JSON
          const excelData = XLSX.utils.sheet_to_json(worksheet);
          console.log(excelData);

          // Cloning the repositories
          for (const entry of excelData) {
            const project = entry['Project Name'];
            const repo = entry['Repository Name'];
            const cloneUrl = `https://:ej4okwddnk5jfd35cjsvur7q5ssg43zeuyjm5xtmg2baim5exxoa@dev.azure.com/rudra099999/${project}/_git/${repo}`;
            
            //Attempt to Clone the repository
            try {
              execSync(`git clone ${cloneUrl}`);
            } catch (error) {
              console.error(`Failed to clone repository: ${project}/${repo}`);
              failedRepos.push({ project, repo });
            }
          }

          // Output failed repositories as CSV
          const csv = failedRepos.map(repo => `${repo.project},${repo.repo}`).join('\n');
          fs.writeFileSync('./failed_repos.csv', csv);

    - name: List cloned repositories
      run: ls
