name: Test Clone

on:
  workflow_dispatch:

jobs:
  test-clone:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: | 
        npm install axios
        npm install nodegit
        npm install child_process

    - name: Set up Git
      run: |
        git config --global user.email "rudra099999@gmail.com"
        git config --global user.name "Rudra Sharans"


    - name: Test Clone
      uses: actions/github-script@v6
      with:
        script: |
          const { execSync } = require('child_process');
          execSync(`git clone https://${{ secrets.ADO_TOKEN }}@dev.azure.com/rudra099999/rudra099999/_git/rudra_repo_2`);
          console.log(execSync('git branch -a', { encoding: 'utf-8' }));
          console.log(execSync('ls', { encoding: 'utf-8' }));
          process.chdir('rudra_repo_2');
          console.log(execSync('ls -lrt', { encoding: 'utf-8' }));

          const defaultBranch = execSync('git symbolic-ref HEAD | sed s#refs/heads/##', { encoding: 'utf-8' }).trim();
          console.log(`Default Branch: ${defaultBranch}`);

          console.log(execSync('git remote -v', { encoding: 'utf-8' }));
          console.log(execSync('git branch -a', { encoding: 'utf-8' }));

          // Create and track branches
          const remoteBranches = execSync('git branch -r | grep -v \'\\->\'', { encoding: 'utf-8' }).split('\n');
          console.log(remoteBranches);
          remoteBranches.forEach(remote => {
              const branchName = remote.replace('origin/', '').trim();
              if (branchName !== defaultBranch && branchName !== 'main') {
                  execSync(`git branch --track ${branchName} ${remote}`);
              }
          });

          console.log(execSync('git branch -a', { encoding: 'utf-8' }));
          
          //execSync(`echo 'This is a test' > data.txt`);
          //console.log(execSync('ls -lrt', { encoding: 'utf-8' }));
          //console.log(execSync('git status', { encoding: 'utf-8' }));
          //execSync('git add .');
          //execSync(`git commit -m 'Adding testing folder'`);
          //execSync('git push');

          //execSync('git remote add github https://github.com/Rudra-SH/rudra_repo_2');
          execSync(`git push https://${{ secrets.TOKEN_GITHUB }}github.com/Rudra-SH/rudra_repo_2.git --all`);
