name: Test SSH Connection

on:
  workflow_dispatch:

jobs:
  test-ssh-connection:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: | 
        npm install @actions/github
        npm install xlsx
        npm install axios

    - name: Test SSH connection
      uses: actions/github-script@v6
      with:
        script: |
          const execSync = require('child_process').execSync;
          execSYnc('mkdir ~/.ssh');
          // import { execSync } from 'child_process';  // replace ^ if using ES modules
          execSync('cat resources/rsa-config-cloud.txt > ~/.ssh/config');

          // Write private key to ~/.ssh/id_rsa
          execSync(`echo "${process.env.ADORSAPRIVATEKEY}" > ~/.ssh/id_rsa`);
          const output = execSync('ls -lrt ~/.ssh');
          console.log(output);


          
