name: For testing Functions

on:
  push:

jobs:
  for-testing-functions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: | 
        npm install @actions/github
        npm install xlsx

    - name: Migrate Bulk repos
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const { execSync } = require('child_process');
          execSync(`mkdir testing_repo`);
          execSync('cat README.md');
          execSync(`ls`);
          execSync('chmod 777 testing_repo');
          execSync(`echo 'Folder created'`);
          // Script for testing functions in javascript
          function multiplyNumbers(a, b) {
              return a * b;
          }

          function addNumbers(a, b) {
            return a + b;
          }
          
          // Example usage:
          const result = addNumbers(multiplyNumbers(2,3),7);
          console.log(result); // Output: 13

    - name: List cloned repositories
      run: |
        cd .
        ls -lrt

